const PAGE_LOAD_TIMEOUT = 2 * 60;

const ELEMENT_TIMEOUT_SHORT = 40;

const ELEMENT_TIMEOUT_LONG = 60;

const DEFAULT_CLOCK_WAIT = 1;

const API_CALL_TIMEOUT = 2 * 60;

module.exports = { PAGE_LOAD_TIMEOUT, ELEMENT_TIMEOUT_SHORT, ELEMENT_TIMEOUT_LONG, DEFAULT_CLOCK_WAIT, API_CALL_TIMEOUT };
